import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: 32,
    marginBottom: 14,
  },
  screenTitle: {
    fontSize: 23,
    color: '#fff',
    fontWeight: 'bold',
  },
  xpTracker: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
  },
  xpCircle: {
    backgroundColor: '#47e2fa',
    borderRadius: 32,
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#47e2fa',
    shadowOpacity: 0.5,
    shadowRadius: 12,
  },
  xpLevel: {
    fontSize: 19,
    color: '#000000ff',
    fontWeight: 'bold',
  },
  xpText: {
    fontSize: 11,
    color: '#080808ff',
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  centerBlock: {
    alignItems: 'center',
    marginBottom: 10,
  },
  userName: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 24,
  },
  subtitle: {
    color: '#d2e7fa',
    fontSize: 13,
  },
  dataBlock: {
    backgroundColor: 'rgba(44,44,44,0.87)',
    borderRadius: 16,
    width: width - 25,
    marginBottom: 14,
    marginLeft : 10,
    padding: 12,
    shadowColor: '#161e2b',
    shadowOpacity: 0.18,
    shadowRadius: 2,
  },
  dataBlockHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  blockLabel: {
    color: '#b8e3fa',
    fontWeight: 'bold',
    fontSize: 15,
    letterSpacing: 0.7,
  },
  dataValue: {
    color: '#f2f6fa',
    fontSize: 15,
    marginBottom: 4,
  },
  input: {
    backgroundColor: '#343536ff',
    color: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 7,
    fontSize: 14,
    marginBottom: 8,
  },
  saveBtn: {
    alignSelf: 'flex-end',
    backgroundColor: '#47e2fa',
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 8,
    marginTop: 5,
  },
  saveBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  profileRoot: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  profileScroll: {
    paddingBottom: 200, // Room for bottom block
  },
  locationBlock: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    backgroundColor: '#47e2fa',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 17,
    paddingHorizontal: 24,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius : 18,
    borderBottomLeftRadius : 18,
    shadowColor: '#47e2fa',
    shadowOpacity: 0.75,
    shadowRadius: 22,
    elevation: 12,
  },
  locationIcon: {
    marginRight: 6,
    textShadowColor: '#070707ff',
    textShadowRadius: 10,
  },
  locationText: {
    color: '#000000ff',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 2,
    letterSpacing: 0.7,
  },
  locationDescription: {
    color: '#090909ff',
    fontSize: 12,
  },
  modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'center',
  alignItems: 'center',
},
modalContent: {
  backgroundColor: '#222',
  borderRadius: 18,
  padding: 28,
  width: '85%',
  alignItems: 'center',
  shadowColor: 'rgba(254, 255, 254, 1)',
  shadowOpacity: 0.9,
  shadowRadius: 15,
  elevation: 15,
},
modalTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#7efcff',
  marginBottom: 12,
  letterSpacing: 0.9,
},
modalText: {
  fontSize: 16,
  color: '#ffffffff',
  marginBottom: 16,
  textAlign: 'center',
},
modalCloseButton: {
  backgroundColor: '#c88048ff',
  paddingHorizontal: 30,
  paddingVertical: 10,
  borderRadius: 12,
},
modalCloseButtonText: {
  color: '#000',
  fontWeight: 'bold',
  fontSize: 16,
},

});
